### ISSUE TITLE
Can you provide two other processed datasets? 

### ISSUE THREAD

**Issue by FC350** [enoche/DGVAE#1]
I didn't get the results I wanted when processing the remaining two data sets. Can you provide two other processed datasets? 
Thank you~

**Comment by enoche** [comment]
Hi, @FC350 Thanks for your interests in the model. Here are the other two datasets:

[Clothing](https://drive.google.com/file/d/1tMscZfm2w6a3vYb_UNSh8PTSkgSR87uY/view)

[Sports](https://drive.google.com/file/d/1zTG1_IEqJ3tMNpBPNTemf4Xavzv8KpXg/view)

**Comment by FC350** [comment]
Thank you very much for providing the datasets.
