### ISSUE TITLE
Could you provide more details of data preprocessing?

### ISSUE THREAD

**Issue by Lyn-L** [enoche/DGVAE#2]
Hi, 

Thanks for this interesting work. Recently, we have been trying to reproduce the results of DGVAE. Using the Baby dataset you provided, the results were well reproduced. However, it has been difficult to reproduce the results on the other two datasets. I suspect that some key steps are missing (refer to the files in [preprocessing]. Could you provide more details on how to process the other datasets? 

Thanks.

**Comment by enoche** [comment]
Hi, @Lyn-L  Thanks for your interests. Here are the other two datasets:

[Clothing](https://drive.google.com/file/d/1tMscZfm2w6a3vYb_UNSh8PTSkgSR87uY/view)

[Sports](https://drive.google.com/file/d/1zTG1_IEqJ3tMNpBPNTemf4Xavzv8KpXg/view)


Also, may I know the reasons on reproducing the results, have you downloaded all raw data and followed the instructions?

**Comment by useranoy2** [comment]
Thank you for doing a great job. Based on the preprocessed data you provided, I can obtain similar results. However, when I tried to generate the corresponding ‘**img2txt**’ file for the new dataset, I encountered a problem. Whether using CLIP or BLIP models, I can only generate some relevant sentences for image data. However, it seems that generating words data for image data is the correct approach. May I ask if you can provide the code for generating img2txt files using the preprocessing model? Thank you very much for your help. Wishing you a happy life!
The relevant code in DGVAE-baby-word-vocab.ipynb is as follows：
# read img txt
topk_img2txt = 20
df_img = pd.read_csv(f' {dataset}- {topk_img2txt}.csv')
df_img['img2txt'] = df_img['img2txt'].fillna(" ")
df_img

How could I get the topk_img2txt?
